### ISSUE TITLE
ASIO on Windows Electron don't working

### ISSUE THREAD

**Issue by alexaf2000** [almogh52/audify#1]
I have been tried the **example loopback** audio from microphone that is in the documentation, and **set the audio api as ASIO** from Windows. But after set it, **if I execute the get api method**, shows me that **still being WASAPI** (the standard Windows API).

Is not finished this ASIO API? Or maybe I'm doing something wrong?

If it's supossed to be finished I can send you more information about the code and my environment.

**Comment by almogh52** [comment]
Apparently, RtAudio's default build options don't compile support for ASIO or DirectSound.
I have added support for those APIs in a different branch and will release it today.
See #2

**Comment by alexaf2000** [comment]
After trying and use it, yes, ASIO driver is now working, or at least at half, because I use ASIO4ALL and the device is detected, but is not opening the ASIO panel settings.
